name: Deploy WordPress with Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux]  # Pastikan runner ini adalah self-hosted

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main  # pastikan branch yang benar, misalnya `main` atau lainnya

    - name: Check if Git is installed
      run: |
        if ! command -v git &> /dev/null; then
          echo "Git not found, installing..."
          sudo apt-get update
          sudo apt-get install -y git
        else
          echo "Git is already installed."
        fi

    - name: Clone the repository
      run: |
        cd
        rm -r aws-ansible-github-action
        git clone https://github.com/excelyno/aws-ansible-github-action.git

    - name: Install Ansible
      run: |
        if ! command -v ansible &> /dev/null; then
          echo "Ansible not found, installing..."
          sudo apt update
          sudo apt install -y ansible
        else
          echo "Ansible is already installed."
        fi

    - name: Copy Ansible inventory and playbook
      run: |
        cd
        pwd
        # Pastikan untuk menyalin file inventory dan playbook ke direktori yang sesuai
        sudo cp aws-ansible-github-action/ansible/inventory ./ansible/inventory
        sudo cp aws-ansible-github-action/ansible/wordpress-playbook.yml ./ansible/wordpress-playbook.yml

    - name: Run Ansible Playbook
      run: |
        cd /home/ubuntu/ansible/
        ansible-playbook -i ./inventory ./wordpress-playbook.yml
