name: Deploy WordPress with Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux]  # Pastikan runner ini adalah self-hosted

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main  # pastikan branch yang benar, misalnya `main` atau lainnya

    - name: Install Ansible
      run: |
        if ! command -v ansible &> /dev/null; then
          echo "Ansible not found, installing..."
          sudo apt update
          sudo apt install -y ansible
        else
          echo "Ansible is already installed."
        fi

    - name: Copy Ansible inventory and playbook
      run: |
        # Pastikan untuk menyalin file inventory dan playbook ke direktori yang sesuai
        pwd
        ls
        cp aws-ansible-github-action/ansible/inventory ./inventory
        cp aws-ansible-github-action/ansible/wordpress-playbook.yml ./wordpress-playbook.yml

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i ./inventory ./wordpress-playbook.yml
