name: Deploy WordPress and Database

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Menggunakan self-hosted runner di control node

    steps:
    - name: Check and Install Ansible
      run: |
        if ! command -v ansible &> /dev/null
        then
            echo "Ansible belum terinstal. Menginstal Ansible sekarang..."
            sudo apt update
            sudo apt install -y ansible
        else
            echo "Ansible sudah terinstal. Versi:"
            ansible --version
        fi

    - name: Configure Ansible Inventory
      run: |
        # Buat inventory file dengan IP EC2 yang sudah ada
        echo "[web]" > ansible/inventory
        echo "172.31.21.248  ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519" >> ansible/inventory
        echo "[db]" >> ansible/inventory
        echo "172.31.28.24 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519" >> ansible/inventory

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i ansible/inventory ansible/wordpress-playbook.yml
